In [1]:
# net level
import pNN_NetLevel_LNC_variation as pNN

# packages
import os
import math
import torch
import random
import pickle
import calendar
import numpy as np
import config
import training_together_variation as training 
import matplotlib.pyplot as plt
from torch.utils.data import TensorDataset, DataLoader
os.environ['KMP_DUPLICATE_LIB_OK']='True'
torch.set_default_tensor_type(torch.FloatTensor)

In [2]:
datasets = os.listdir('./dataset')
datasets = [f for f in datasets if (f.startswith('Dataset') and f.endswith('.p'))] 
#datasets

In [3]:

#result = torch.zeros((13, 1, 10))
lrs = [0]
for i in range(len(datasets)):
    dataset = datasets[i]
    datapath = os.path.join(f'./dataset/{dataset}')
    with open(datapath, 'rb') as f:
        data = pickle.load(f)
    X_train    = data['X_train']
    y_train    = data['y_train']
    X_valid    = data['X_valid']
    y_valid    = data['y_valid']
    X_test     = data['X_test']
    y_test     = data['y_test']
    data_name  = data['name']

    N_class    = data['n_class']
    N_feature  = data['n_feature']
    N_train    = X_train.shape[0]
    N_valid    = X_valid.shape[0]
    N_test     = X_test.shape[0]
    
    # generate tensordataset
    trainset = TensorDataset(X_train, y_train)
    validset = TensorDataset(X_valid, y_valid)
    testset  = TensorDataset(X_test, y_test)

    # batch
    train_loader = DataLoader(trainset, batch_size=N_train)
    valid_loader = DataLoader(validset, batch_size=N_valid)
    test_loader  = DataLoader(testset,  batch_size=N_test)
    
    for j in range(len(lrs)):
        lr = lrs[j]
        
        #for n in range(10):
        seed = 0      
            
        setup = f'dataset_{data_name}_seed_{seed}_nonlearnable1'
        print(setup)
            
        if os.path.exists(f'./results_variation/pNN_{setup}'):
            print('File exists, pass.')
        else:
            torch.manual_seed(seed)
            model = pNN.pNN([N_feature, 3, N_class], 1, 0)
    
            optimizer = torch.optim.Adam([{'params':model.GetParam('theta_'),'lr':1e-1},
                                  {'params':model.GetParam('eta_'), 'lr':lr},
                                  {'params':model.GetParam('inv_'),'lr':lr}])
    
    
            NN, acc_valid = training.training_pNN(model, train_loader, valid_loader, optimizer, pNN.lossfunction)
                #result[i,j,n] = acc_valid
            torch.save(NN, f'./results_variation/pNN_{setup}')
#a = {'acc_valid': result}
#with open('acc_valid_0.0005_learnable.txt', 'wb') as file:
    #pickle.dump(a, file)

dataset_acuteinflammation_seed_0_nonlearnable1
| Epoch:        0 | Valid accuracy: 0.86957 | Valid loss: 0.676321149 |
| Epoch:     5000 | Valid accuracy: 1.00000 | Valid loss: 0.000000000 |
dataset_balancescale_seed_0_nonlearnable1
| Epoch:        0 | Valid accuracy: 0.41935 | Valid loss: 0.713952243 |
| Epoch:     5000 | Valid accuracy: 0.96774 | Valid loss: 0.048945166 |
dataset_breastcancerwisc_seed_0_nonlearnable1
| Epoch:        0 | Valid accuracy: 0.66187 | Valid loss: 0.698530138 |
| Epoch:     5000 | Valid accuracy: 0.94964 | Valid loss: 0.090649277 |
dataset_cardiotocography3clases_seed_0_nonlearnable1
| Epoch:        0 | Valid accuracy: 0.74528 | Valid loss: 0.702790558 |
| Epoch:     5000 | Valid accuracy: 0.90566 | Valid loss: 0.169152781 |
dataset_energyy1_seed_0_nonlearnable1
| Epoch:        0 | Valid accuracy: 0.20261 | Valid loss: 0.725977361 |
| Epoch:     5000 | Valid accuracy: 0.84314 | Valid loss: 0.240390152 |
| Epoch:    10000 | Valid accuracy: 0.87582 | Valid lo

In [5]:
result.shape, result

(torch.Size([13, 1, 10]),
 tensor([[[1.0000, 1.0000, 0.8696, 1.0000, 1.0000, 0.8696, 1.0000, 1.0000,
           1.0000, 1.0000]],
 
         [[0.8952, 0.8952, 0.9919, 0.9758, 0.9032, 0.9032, 0.9758, 0.9032,
           0.9516, 0.9032]],
 
         [[0.9353, 0.9209, 0.9353, 0.9353, 0.9784, 0.9712, 0.9856, 0.9712,
           0.9281, 0.9784]],
 
         [[0.8420, 0.8585, 0.8774, 0.8160, 0.8090, 0.8113, 0.7453, 0.8066,
           0.8561, 0.7453]],
 
         [[0.7974, 0.7974, 0.8431, 0.8824, 0.8105, 0.8693, 0.7974, 0.8497,
           0.8889, 0.7974]],
 
         [[0.9216, 0.9281, 0.7386, 0.7386, 0.9346, 0.9216, 0.9346, 0.8693,
           0.8693, 0.9216]],
 
         [[1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
           1.0000, 1.0000]],
 
         [[0.8220, 0.8377, 0.8377, 0.8534, 0.8220, 0.8168, 0.8377, 0.8272,
           0.8325, 0.8534]],
 
         [[0.1115, 0.3612, 0.6324, 0.4873, 0.3790, 0.6629, 0.6815, 0.5150,
           0.6001, 0.5510]],
 
         [[0.9512, 0

In [6]:
result.mean()

tensor(0.8164)

## valid_acc

In [6]:

acc = torch.zeros((13, 1, 10))
#lrs = [0.0005]
for i in range(len(datasets)):
    dataset = datasets[i]
    datapath = os.path.join(f'./dataset/{dataset}')
    with open(datapath, 'rb') as f:
        data = pickle.load(f)
    X_train    = data['X_train']
    y_train    = data['y_train']
    X_valid    = data['X_valid']
    y_valid    = data['y_valid']
    X_test     = data['X_test']
    y_test     = data['y_test']
    data_name  = data['name']

    N_class    = data['n_class']
    N_feature  = data['n_feature']
    N_train    = X_train.shape[0]
    N_valid    = X_valid.shape[0]
    N_test     = X_test.shape[0]
    
    # generate tensordataset
    trainset = TensorDataset(X_train, y_train)
    validset = TensorDataset(X_valid, y_valid)
    testset  = TensorDataset(X_test, y_test)

    # batch
    train_loader = DataLoader(trainset, batch_size=N_train)
    valid_loader = DataLoader(validset, batch_size=N_valid)
    test_loader  = DataLoader(testset,  batch_size=N_test)
    
    for j in range(len(lrs)):
        lr = lrs[j]
        
        for n in range(10):
            seed = n      
            setup = f'dataset_{data_name}_seed_{seed}_nonlearnable1'
            model = torch.load(f'./results_variation/pNN_{setup}')
            
            
            with torch.no_grad():
                for X_valid, y_valid in valid_loader:
                
                    prediction_valid = model(X_valid)
                    #acc_valid = lossfunction(prediction_valid, y_valid)
                    yhat_valid = torch.argmax(prediction_valid.data, 2)
                
                    yy_valid = y_valid.repeat(prediction_valid.shape[0], 1)
                    valid_correct = torch.sum(yhat_valid == yy_valid.data)
                    acc_valid = valid_correct / (y_valid.numel() * prediction_valid.shape[0])
                    acc[i,j,n] = acc_valid
                    

In [7]:
acc,acc.shape

(tensor([[[1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
           1.0000, 1.0000]],
 
         [[0.9677, 0.8952, 0.9677, 0.8710, 0.9677, 0.9677, 0.9677, 0.8952,
           0.9677, 0.8952]],
 
         [[0.9496, 0.9640, 0.9712, 0.9496, 0.9496, 0.9640, 0.9712, 0.9640,
           0.9568, 0.9496]],
 
         [[0.8986, 0.8703, 0.9033, 0.8774, 0.9104, 0.8703, 0.8797, 0.8750,
           0.8939, 0.8726]],
 
         [[0.8431, 0.8758, 0.8758, 0.8889, 0.8824, 0.8824, 0.8824, 0.8824,
           0.8431, 0.8431]],
 
         [[0.9281, 0.9150, 0.9281, 0.9281, 0.9281, 0.9085, 0.9412, 0.9281,
           0.9216, 0.9216]],
 
         [[0.9655, 1.0000, 1.0000, 1.0000, 1.0000, 0.9655, 1.0000, 1.0000,
           0.9655, 1.0000]],
 
         [[0.8377, 0.8272, 0.8429, 0.8220, 0.8220, 0.8429, 0.8220, 0.8429,
           0.8377, 0.8377]],
 
         [[0.3999, 0.4249, 0.4945, 0.4877, 0.5428, 0.4759, 0.5537, 0.4595,
           0.3999, 0.4786]],
 
         [[0.9268, 0.9512, 0.9512, 0.9268, 0.9

In [12]:
acc.mean()

tensor(0.8671)

In [8]:
acc[:,0,:].argmax(dim=1)

tensor([0, 0, 2, 4, 3, 6, 1, 2, 6, 1, 0, 0, 3])

## variation

In [7]:
result1 = result[:13, 0, :]
result1.shape

torch.Size([13, 10])

In [8]:
index1 = torch.argmax(result1, dim = 1)
index1

tensor([0, 2, 6, 2, 8, 4, 0, 3, 6, 0, 2, 2, 2])

In [16]:
results_test= torch.zeros((13,3,2))
test_epsilons = [0, 0.05, 0.1]
for d, dataset in enumerate(datasets):
        datapath = os.path.join(f'./dataset/{dataset}')
        with open(datapath, 'rb') as f:
            data = pickle.load(f)
        X_train    = data['X_train']
        y_train    = data['y_train']
        X_valid    = data['X_valid']
        y_valid    = data['y_valid']
        X_test     = data['X_test']
        y_test     = data['y_test']
        data_name  = data['name']

        N_class    = data['n_class']
        N_feature  = data['n_feature']
        N_train    = X_train.shape[0]
        N_valid    = X_valid.shape[0]
        N_test     = X_test.shape[0]

        # generate tensordataset
        trainset = TensorDataset(X_train, y_train)
        validset = TensorDataset(X_valid, y_valid)
        testset  = TensorDataset(X_test, y_test)

        # batch
        train_loader = DataLoader(trainset, batch_size=N_train)
        valid_loader = DataLoader(validset, batch_size=N_valid)
        test_loader  = DataLoader(testset,  batch_size=N_test)

        #for s, seed in enumerate(index1):
        setup = f'dataset_{data_name}_lr_0.001_seed_{index1[d]}_learnable'
        #setup = f'dataset_{data_name}_lr_0.001_seed_{seed}_learnable'
        model = torch.load(f'./results_variation/pNN_{setup}')
        
            
            
        with torch.no_grad():
            for X_test, y_test in test_loader:
                
                
                for i in range(len(test_epsilons)):
                    test_epsilon = test_epsilons[i]
                    if test_epsilon == 0:
                        model.SetParameter('N', 1)
                    else:
                        model.SetParameter('N', 100)
                    model.SetParameter('epsilon', test_epsilon)
                    BASIC_variation(model, X_test, y_test)
                    acc, std = BASIC_variation(model, X_test, y_test)
                    results_test[d,i,0], results_test[d,i,1] = acc, std
#results_test[d,0,0], results_test[d,0,0]

(tensor(0.7937), tensor(0.7937))

In [19]:
a=results_test[:,0,:]
a

tensor([[1.0000, 0.0000],
        [0.9444, 0.0000],
        [0.9643, 0.0000],
        [0.8521, 0.0000],
        [0.9416, 0.0000],
        [0.9286, 0.0000],
        [0.9677, 0.0000],
        [0.8083, 0.0000],
        [0.6776, 0.0000],
        [0.8605, 0.0000],
        [0.9688, 0.0000],
        [0.7937, 0.0000],
        [0.7937, 0.0000]])

In [21]:
a[:,0].mean()

tensor(0.8847)

In [22]:
b =[1.0,0.8809,0.9571,0.8756,0.9286,0.9156,0.9677,0.7979,0.7876,0.7674,1.0,0.8095,0.7936]
b

[1.0,
 0.8809,
 0.9571,
 0.8756,
 0.9286,
 0.9156,
 0.9677,
 0.7979,
 0.7876,
 0.7674,
 1.0,
 0.8095,
 0.7936]

In [25]:
res = 0
for i in b:
    res += i
c = res/len(b)
c

0.8831923076923077

In [9]:
def basic(prediction, y, *args, **kwargs):
    act, idx = torch.max(prediction, dim=1)
    corrects = (y.view(-1) == idx)
    return corrects.float().sum().item() / y.numel()

In [15]:
def BASIC_variation(nn, x, y, *args, **kwargs):
    prediction = nn(x)
    N = prediction.shape[0]
    accs = []
    for n in range(N):
        accs.append(basic(prediction[n,:,:], y))
    return np.mean(accs), np.std(accs)

## 5% variation

In [26]:
results_test[:,1,:]

tensor([[0.9528, 0.0758],
        [0.8999, 0.0361],
        [0.9361, 0.0831],
        [0.7293, 0.1620],
        [0.8890, 0.0800],
        [0.8464, 0.0447],
        [0.8252, 0.1559],
        [0.6822, 0.1139],
        [0.5308, 0.1287],
        [0.8435, 0.1195],
        [0.6460, 0.1831],
        [0.7338, 0.0781],
        [0.6211, 0.1686]])

In [27]:
results_test[:,2,:]

tensor([[0.7836, 0.2407],
        [0.8271, 0.1272],
        [0.7494, 0.2661],
        [0.5813, 0.2702],
        [0.8242, 0.1485],
        [0.8262, 0.0579],
        [0.7271, 0.2221],
        [0.6078, 0.1166],
        [0.3623, 0.1839],
        [0.6984, 0.2225],
        [0.5281, 0.1506],
        [0.7008, 0.0842],
        [0.5119, 0.1965]])

##  learnable

In [47]:
result5 = result[:13,0,:]
result5

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000],
        [0.9565, 0.9694, 0.9621, 0.9605, 0.9605, 0.9629, 0.9613, 0.9548, 0.8685,
         0.9540],
        [0.9633, 0.9295, 0.9309, 0.9273, 0.9331, 0.9266, 0.9288, 0.9223, 0.9259,
         0.9317],
        [0.8642, 0.8625, 0.8644, 0.8663, 0.8644, 0.8566, 0.8792, 0.8710, 0.8821,
         0.8625],
        [0.8673, 0.8379, 0.8477, 0.8647, 0.8647, 0.8725, 0.8386, 0.8412, 0.8431,
         0.8386],
        [0.7373, 0.8935, 0.9046, 0.8922, 0.7386, 0.7386, 0.7386, 0.9007, 0.9137,
         0.9085],
        [0.9862, 0.9862, 0.9793, 0.9966, 0.9862, 0.9828, 0.9897, 0.9828, 0.9931,
         0.9828],
        [0.8089, 0.8110, 0.8178, 0.8136, 0.8168, 0.8105, 0.8147, 0.8047, 0.8037,
         0.8136],
        [0.6122, 0.6015, 0.6426, 0.4105, 0.6111, 0.5569, 0.6090, 0.4217, 0.4758,
         0.5981],
        [0.9317, 0.9317, 0.9488, 0.9439, 0.9195, 0.9317, 0.9341, 0.9341, 0.9415,
         0.9439],
        [0

In [49]:
index5 = torch.argmax(result5, dim = 1)
index5

tensor([0, 1, 0, 8, 5, 8, 3, 2, 2, 2, 1, 4, 6])

In [62]:
#result_test1= torch.zeros((13,100))
acc_test5 =[]
for d, dataset in enumerate(datasets):
        datapath = os.path.join(f'./dataset/{dataset}')
        with open(datapath, 'rb') as f:
            data = pickle.load(f)
        X_train    = data['X_train']
        y_train    = data['y_train']
        X_valid    = data['X_valid']
        y_valid    = data['y_valid']
        X_test     = data['X_test']
        y_test     = data['y_test']
        data_name  = data['name']

        N_class    = data['n_class']
        N_feature  = data['n_feature']
        N_train    = X_train.shape[0]
        N_valid    = X_valid.shape[0]
        N_test     = X_test.shape[0]

        # generate tensordataset
        trainset = TensorDataset(X_train, y_train)
        validset = TensorDataset(X_valid, y_valid)
        testset  = TensorDataset(X_test, y_test)

        # batch
        train_loader = DataLoader(trainset, batch_size=N_train)
        valid_loader = DataLoader(validset, batch_size=N_valid)
        test_loader  = DataLoader(testset,  batch_size=N_test)

        #for s, seed in enumerate(index1):
        setup =  f'dataset\uf022{data_name}_epsilon\uf0220.1_seed\uf022{index5[d]}'
        model = torch.load(f'./results_variation/pNN_{setup}')
            
            
        with torch.no_grad():
            for X_test, y_test in test_loader:
                
            #model.SetParameter('N', config.N_test)
            #model.SetParameter('epsilon', test_epsilon)
                accs = []
                for i in range(10):
                    BASIC_variation(model, X_test, y_test, accs)
                    #accs = BASIC_variation(model, X_test, y_test, accs)
                #acc, std, length = BASIC_variation(model, X_test, y_test, accs)
                acc_test5.append(np.mean(accs))
                print(np.mean(accs), np.std(accs), len(accs))
            #results[d,s,e,0], results[d,s,e,1] = acc, std
print(np.mean(acc_test5))

0.9832 0.05605140497793074 100
0.8732539682539684 0.01876291862004291 100
0.8678571428571428 0.17130799330862692 100
0.8308685446009388 0.02903097302359705 100
0.8784415584415587 0.024931682671042895 100
0.8574025974025973 0.03939070440073436 100
0.8748387096774194 0.09914095117453675 100
0.7802072538860103 0.01975962288223707 100
0.4758890404729421 0.07638018363583102 100
0.8369767441860464 0.08772683646791596 100
0.7967187499999998 0.07567496842651583 100
0.6749206349206349 0.04889713391616547 100
0.7785714285714284 0.0859014710945371 100
0.8083958748669761


In [19]:
results_test= torch.zeros((13,2,2))
test_epsilons = [0.05, 0.1]
for d, dataset in enumerate(datasets):
        datapath = os.path.join(f'./dataset/{dataset}')
        with open(datapath, 'rb') as f:
            data = pickle.load(f)
        X_train    = data['X_train']
        y_train    = data['y_train']
        X_valid    = data['X_valid']
        y_valid    = data['y_valid']
        X_test     = data['X_test']
        y_test     = data['y_test']
        data_name  = data['name']

        N_class    = data['n_class']
        N_feature  = data['n_feature']
        N_train    = X_train.shape[0]
        N_valid    = X_valid.shape[0]
        N_test     = X_test.shape[0]

        # generate tensordataset
        trainset = TensorDataset(X_train, y_train)
        validset = TensorDataset(X_valid, y_valid)
        testset  = TensorDataset(X_test, y_test)

        # batch
        train_loader = DataLoader(trainset, batch_size=N_train)
        valid_loader = DataLoader(validset, batch_size=N_valid)
        test_loader  = DataLoader(testset,  batch_size=N_test)

        #for s, seed in enumerate(index1):
        setup = f'dataset_{data_name}__lr_0.0005_seed_{index1[d]}_learnable'
        model = torch.load(f'./results_variation/pNN_{setup}')
        
            
            
        with torch.no_grad():
            for X_test, y_test in test_loader:
                
                model.SetParameter('N', 100)
                for i in range(len(test_epsilons)):
                    test_epsilon = test_epsilons
                    model.SetParameter('epsilon', test_epsilon)
                    BASIC_variation(model, X_test, y_test, accs)
                    acc, std = BASIC_variation(model, X_test, y_test)
                    results_test[d,i,0], results_test[d,i,1] = acc, std
results_test[d,0,0], results_test[d,0,0]

AttributeError: 'pLayer' object has no attribute 'SetParameter'

In [ ]:
with open('invWithoutR1234_dataset.txt', 'rb') as file2:
    b = pickle.load(file2)
YY = b['Y']
YY.shape